import type { Profile, Conversation, Message, AdminStats } from './types'

export const MOCK_PROFILES: Profile[] = [
  {
    id: '1',
    email: 'rafael@example.com',
    full_name: 'Rafael Mendes',
    avatar_url: null,
    city: 'São Paulo',
    state: 'SP',
    country: 'BR',
    linkedin_url: 'https://linkedin.com/in/rafaelmendes',
    bio: 'Builder apaixonado por fintech. Fundei 2 startups e busco um CTO técnico para minha próxima venture no setor de crédito.',
    role: 'founder',
    skills: ['Product Management', 'Vendas', 'Finanças'],
    interests: ['Fintech', 'SaaS', 'Marketplace'],
    available_capital: 150000,
    availability: 'full_time',
    project_description: 'Plataforma de crédito para MEIs com análise de risco por IA.',
    is_verified: true,
    is_premium: true,
    created_at: '2024-01-15T00:00:00Z',
    updated_at: '2024-06-01T00:00:00Z',
    match_score: 94,
  },
  {
    id: '2',
    email: 'ana@example.com',
    full_name: 'Ana Ferreira',
    avatar_url: null,
    city: 'Florianópolis',
    state: 'SC',
    country: 'BR',
    linkedin_url: 'https://linkedin.com/in/anaferreira',
    bio: 'Engenheira de Software com 8 anos de experiência. Especialista em sistemas distribuídos e IA. Quero co-fundar uma startup de healthtech.',
    role: 'developer',
    skills: ['Python', 'Machine Learning', 'AWS', 'Node.js'],
    interests: ['Healthtech', 'Inteligência Artificial', 'SaaS'],
    available_capital: null,
    availability: 'part_time',
    project_description: null,
    is_verified: true,
    is_premium: false,
    created_at: '2024-02-10T00:00:00Z',
    updated_at: '2024-05-20T00:00:00Z',
    match_score: 89,
  },
  {
    id: '3',
    email: 'carlos@example.com',
    full_name: 'Carlos Investimentos',
    avatar_url: null,
    city: 'Rio de Janeiro',
    state: 'RJ',
    country: 'BR',
    linkedin_url: 'https://linkedin.com/in/carlosinv',
    bio: 'Angel investor com portfolio de 12 startups. Ticket médio de R$200K. Foco em B2B SaaS e Fintech early stage.',
    role: 'investor',
    skills: ['Finanças', 'Operações', 'Marketing Digital'],
    interests: ['Fintech', 'SaaS', 'Agritech'],
    available_capital: 500000,
    availability: 'flexible',
    project_description: null,
    is_verified: true,
    is_premium: true,
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-06-10T00:00:00Z',
    match_score: 87,
  },
  {
    id: '4',
    email: 'julia@example.com',
    full_name: 'Júlia Rodrigues',
    avatar_url: null,
    city: 'Belo Horizonte',
    state: 'MG',
    country: 'BR',
    linkedin_url: 'https://linkedin.com/in/juliarodrigues',
    bio: 'UX Designer com foco em produtos B2C. Criei experiências para +2M de usuários. Procuro fundador técnico para construir um app de bem-estar.',
    role: 'founder',
    skills: ['UX/UI Design', 'Branding', 'Marketing Digital', 'Copywriting'],
    interests: ['Healthtech', 'Edtech', 'Entretenimento'],
    available_capital: 50000,
    availability: 'full_time',
    project_description: 'App de saúde mental para jovens profissionais com IA terapêutica.',
    is_verified: false,
    is_premium: false,
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-06-05T00:00:00Z',
    match_score: 82,
  },
  {
    id: '5',
    email: 'pedro@example.com',
    full_name: 'Pedro Alves',
    avatar_url: null,
    city: 'Curitiba',
    state: 'PR',
    country: 'BR',
    linkedin_url: 'https://linkedin.com/in/pedroalves',
    bio: 'Serial entrepreneur com 15 anos de experiência. Parceiro estratégico para startups em fase de go-to-market e expansão.',
    role: 'strategic_partner',
    skills: ['Vendas', 'Operações', 'Marketing Digital', 'Growth Hacking'],
    interests: ['Marketplace', 'E-commerce', 'Logística', 'SaaS'],
    available_capital: 100000,
    availability: 'part_time',
    project_description: null,
    is_verified: true,
    is_premium: true,
    created_at: '2024-02-20T00:00:00Z',
    updated_at: '2024-05-30T00:00:00Z',
    match_score: 78,
  },
]

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv1',
    participants: ['me', '1'],
    last_message: {
      id: 'msg1',
      conversation_id: 'conv1',
      sender_id: '1',
      content: 'Olá! Vi seu perfil e achei incrível o que você está construindo. Podemos conversar?',
      status: 'read',
      created_at: '2024-06-28T14:30:00Z',
    },
    unread_count: 0,
    created_at: '2024-06-28T14:00:00Z',
    updated_at: '2024-06-28T14:30:00Z',
    other_user: MOCK_PROFILES[0],
  },
  {
    id: 'conv2',
    participants: ['me', '3'],
    last_message: {
      id: 'msg2',
      conversation_id: 'conv2',
      sender_id: 'me',
      content: 'Interessante! Me conta mais sobre seu critério de investimento.',
      status: 'delivered',
      created_at: '2024-06-27T16:45:00Z',
    },
    unread_count: 2,
    created_at: '2024-06-27T15:00:00Z',
    updated_at: '2024-06-27T16:45:00Z',
    other_user: MOCK_PROFILES[2],
  },
  {
    id: 'conv3',
    participants: ['me', '2'],
    last_message: {
      id: 'msg3',
      conversation_id: 'conv3',
      sender_id: '2',
      content: 'Seria ótimo conversar sobre a stack técnica do projeto!',
      status: 'read',
      created_at: '2024-06-26T10:00:00Z',
    },
    unread_count: 0,
    created_at: '2024-06-26T09:00:00Z',
    updated_at: '2024-06-26T10:00:00Z',
    other_user: MOCK_PROFILES[1],
  },
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    conversation_id: 'conv1',
    sender_id: '1',
    content: 'Olá! Vi seu perfil e achei incrível o que você está construindo. Podemos conversar?',
    status: 'read',
    created_at: '2024-06-28T14:00:00Z',
    sender: MOCK_PROFILES[0],
  },
  {
    id: 'msg-2',
    conversation_id: 'conv1',
    sender_id: 'me',
    content: 'Claro! Fico feliz que tenha gostado. O que te chamou mais atenção no meu perfil?',
    status: 'read',
    created_at: '2024-06-28T14:10:00Z',
  },
  {
    id: 'msg-3',
    conversation_id: 'conv1',
    sender_id: '1',
    content: 'A combinação de skills técnicas com visão de produto é exatamente o que procuro para o meu projeto de fintech. Você tem experiência com sistemas de crédito?',
    status: 'read',
    created_at: '2024-06-28T14:20:00Z',
    sender: MOCK_PROFILES[0],
  },
  {
    id: 'msg-4',
    conversation_id: 'conv1',
    sender_id: 'me',
    content: 'Sim, trabalhei 3 anos numa fintech de antecipação de recebíveis. Temos muito a trocar!',
    status: 'read',
    created_at: '2024-06-28T14:25:00Z',
  },
  {
    id: 'msg-5',
    conversation_id: 'conv1',
    sender_id: '1',
    content: 'Olá! Vi seu perfil e achei incrível o que você está construindo. Podemos conversar?',
    status: 'read',
    created_at: '2024-06-28T14:30:00Z',
    sender: MOCK_PROFILES[0],
  },
]

export const MOCK_ADMIN_STATS: AdminStats = {
  total_users: 5247,
  active_users: 3891,
  total_matches: 12483,
  total_messages: 89234,
  premium_users: 847,
  verified_users: 2103,
  new_users_today: 47,
  new_matches_today: 156,
}
